/* eslint-disable */
/* Throw-away API stand-in for the end-to-end tests. Never deployed. */
const http=require('http');
const imgs=['Farshi-Shalwar-Suit/IMG-20260824-WA0055.jpg','Frock-Suit/IMG-20260824-WA0019.jpg','Garara-Suit/IMG-20260824-WA0003.jpg','Gown/IMG-20260824-WA0015.jpg','Lehnga/IMG-20260824-WA0004.jpg','Pant-Suit/IMG-20260824-WA0021.jpg','Plazo-Suit/IMG-20260824-WA0017.jpg','Sharara-Suit/IMG-20260824-WA0016.jpg'];
const names=['Ivory Noor Kurta Set','Rosewater Frock Suit','Champagne Garara Set','Dusk Embroidered Gown','Clay Lehenga Set','Sand Pant Suit','Mulmul Plazo Suit','Sharara With Dupatta'];
if(process.env.LONGN){names[0]='Ivory Noor Embroidered Chanderi Silk Anarkali Kurta Set With Dupatta And Palazzo Pants';names[1]='Rosewater Frock Suit';names[2]='Champagne Garara Set With Hand Embroidered Gota Patti Work And Matching Dupatta For Weddings';}
const products=imgs.map((im,i)=>({id:'p'+i,_id:'p'+i,slug:'p'+i,name:names[i],categoryId:'c1',
 pricing:{mrp:6999+i*500,sellingPrice:4999+i*400,currency:'INR'},
 inventory:{stock:i==5?0:12,reserved:0,lowStockThreshold:3},
 content:{description:'Hand finished contemporary Indian womenswear.',descriptionFormat:'plain'},
 media:[{id:'m'+i,type:'image',src:'/images/products/'+im,alt:names[i],sortOrder:0,isPrimary:true},{id:'n'+i,type:'image',src:'/images/products/'+imgs[(i+1)%8],alt:names[i],sortOrder:1,isPrimary:false}],
 merchandising:{isNew:i<3,isFeatured:i%2==0,isBestSeller:i>4,badges:i<2?['new']:i==6?['best-seller']:[],ranking:i},
 status:'active',createdAt:'2026-01-01',updatedAt:'2026-01-01',
 availability:{isSoldOut:i==5,isInStock:i!=5,isLowStock:i==3,availableQuantity:i==5?0:12}}));
if(process.env.MEDIAX){const p3=products[3];p3.media=[0,1,2,3,4].map(k=>({id:'x'+k,type:'image',src:'/images/products/'+imgs[(3+k)%8],alt:'view '+k,sortOrder:k,isPrimary:k==0})).concat([{id:'v1',type:'video',src:'/videos/jannat-elegance.mp4',poster:'/images/products/'+imgs[3],alt:'film',sortOrder:5,isPrimary:false}]);p3.availability.isLowStock=false;}
const cats=[{id:'c1',name:'Suits',slug:'suits',description:'',image:'/images/products/'+imgs[2],sortOrder:1,isFeatured:true,isActive:true}];
if(process.env.MOREC){const nm=[['Suits','suits'],['Garara','garara'],['Festive','festive'],['Ethnic','ethnic'],['Contemporary','contemporary'],['Gown','gown'],['Frock','frock'],['Kurta Sets','kurta-sets']];cats.length=0;nm.forEach((n,k)=>cats.push({id:'c'+(k+1),name:n[0],slug:n[1],description:k%2?'Hand finished '+n[0].toLowerCase()+' for every occasion.':'',image:'/images/products/'+imgs[k%imgs.length],sortOrder:k,isFeatured:true,isActive:true}));}
http.createServer((q,r)=>{
 if(process.env.NOAUTH && (q.url.includes('/auth/')||q.url.includes('/carts')||q.url.includes('/customer')||q.url.includes('/orders/my'))){r.statusCode=401;r.setHeader('content-type','application/json');return r.end(JSON.stringify({success:false,error:{code:'UNAUTHORIZED',message:'Unauthorized'}}));}
 /*REQLOG*/ if(q.method!=='OPTIONS') console.log(q.method+' '+q.url);
 if(process.env.FAIL && q.url.includes('/api/products')){r.statusCode=500;r.setHeader('content-type','application/json');return r.end(JSON.stringify({success:false,error:{message:'boom'}}));}
 r.setHeader('Access-Control-Allow-Origin','http://localhost:3111');r.setHeader('Access-Control-Allow-Credentials','true');r.setHeader('Access-Control-Allow-Headers','content-type,authorization');r.setHeader('Access-Control-Allow-Methods','GET,POST,PATCH,PUT,DELETE,OPTIONS');
 if(q.method==='OPTIONS'){r.statusCode=204;return r.end();}
 const u=q.url.split('?')[0]; let data={};
 const user={id:'u1',name:'Aisha Khan',email:'aisha@example.com',phone:'9876543210',avatarUrl:'',role:'customer',status:'active',emailVerified:false,phoneVerified:true,createdAt:'2026-01-01',updatedAt:'2026-01-01'};
 const cp=i=>({_id:'p'+i,id:'p'+i,slug:'p'+i,name:names[i],categoryId:'c1',pricing:products[i].pricing,inventory:products[i].inventory,media:[{url:products[i].media[0].src,alt:names[i]}],status:'active'});

 const J=d=>{r.setHeader('content-type','application/json');return r.end(JSON.stringify({success:true,data:d}));};
 const order=(n,st)=>Object.assign((x=>x)({id:'o'+n,orderNumber:'AF-100'+n,customerName:'Aisha Khan',customerEmail:'aisha@example.com',customerPhone:'9876543210',shippingAddress:{firstName:'Aisha',lastName:'Khan',addressLine1:'12 Rose Lane',landmark:'Near park',city:'Delhi',state:'Delhi',postalCode:'110009',country:'India'},deliveryMethod:'standard',shippingAmount:0,subtotal:4999,mrpTotal:6999,productDiscount:2000,couponDiscount:0,total:4999,currency:'INR',paymentMethod:'cod',paymentStatus:'pending',status:st,items:[{productId:'p0',sku:'P0',name:names[0],slug:'p0',image:'/images/products/'+imgs[0],mrp:6999,sellingPrice:4999,currency:'INR',quantity:1,lineTotal:4999}],createdAt:'2026-09-01T10:00:00Z',shippingInfo:{courierName:'BlueDart',trackingNumber:'BD123456'}}),(process.env.PAIDMODE&&n==1)?{paymentMethod:'bank_upi',paymentStatus:'paid',status:'confirmed',paymentWhatsapp:'9876543210'}:(process.env.BANKMODE&&n==1)?{paymentMethod:'bank_upi',paymentStatus:'pending',status:'confirmed',paymentWhatsapp:'9876543210',paymentExpiresAt:new Date(Date.now()+22*60000).toISOString()}:{});//BANKMODE
 if(u.endsWith('/customer/profile')) return J({user,customer:{id:'c1',userId:'u1',phone:'9876543210',dateOfBirth:'1994-05-12',gender:'female',preferredSizes:['M'],preferredColors:['Ivory'],marketingEmails:true,marketingWhatsapp:false,lastOrderAt:'2026-09-01',totalOrders:3,totalSpent:14997,status:'active',createdAt:'2026-01-01',updatedAt:'2026-01-01'}});
 if(q.method==='POST'&&u.endsWith('/send-invoice')){global.__i=(global.__i||0);const seq=(process.env.INVSEQ||'ok').split(',');const m=seq[Math.min(global.__i++,seq.length-1)];const E=(c,code,msg)=>{r.statusCode=c;r.setHeader('content-type','application/json');return r.end(JSON.stringify({success:false,error:{code,message:msg}}));};if(m==='ok')return J({sent:true,sentAt:new Date().toISOString()});if(m==='429')return E(429,'BILL_RATE_LIMITED','The invoice was sent a moment ago.');if(m==='401')return E(401,'INVALID_ACCESS_TOKEN','Invalid or expired access token.');return E(502,'WHATSAPP_FAILED','We could not send the invoice on WhatsApp right now. Please try again shortly.');}
 if(u.endsWith('/orders/my-orders')) {r.setHeader('content-type','application/json');return r.end(JSON.stringify({success:true,data:{orders:[order(1,'shipped'),order(2,'delivered'),order(3,'processing')]}}));}
 if(u.includes('/orders/my-orders/')||u.includes('/orders/AF')) {r.setHeader('content-type','application/json');return r.end(JSON.stringify({success:true,data:{order:order(1,'shipped')}}));}
 if(u.includes('/payments/bank-upi'))return J({sent:true,orderNumber:'AF-1001',paymentClaimedAt:new Date().toISOString()});
 if(u.endsWith('/products/insights')){const o={};['p0','p1','p2','p3','p4','p5','p6','p7'].forEach((id,i)=>{o[id]={rating:i%3==2?0:4.2+i*0.1,reviews:i%3==2?0:3+i*2,soldLast7Days:i%2==0?7+i:1}});return J(o);}
 if(u.endsWith('/reviews/mine')) return J([]);
 if(u.includes('/social-proof')) return J({soldLast7Days:7,ordersLast7Days:5});
 if(u.includes('/stock-alert')) return J({subscribed:true});
 if(u.includes('/reviews/featured')) return J({summary:{total:12,average:4.6},reviews:[0,1,2].map(i=>({id:'r'+i,productId:'p'+i,rating:5-(i==2?1:0),title:['Beautiful fabric','Perfect for Eid','Lovely fit'][i],body:'Absolutely loved the fit and finishing. Arrived quickly and looked even better than the photos.',verifiedPurchase:true,authorName:['Aisha K.','Sana R.','Meher A.'][i],createdAt:'2026-09-01',productName:names[i],productImage:'/images/products/'+imgs[i]}))});
 if(u.includes('/reviews/product/')) return J({reviews:[{id:'r1',productId:'p0',rating:5,title:'Lovely',body:'Beautiful fabric and fit.',verifiedPurchase:true,media:[],authorName:'Aisha K.',createdAt:'2026-09-01'}],summary:{total:12,average:4.6,distribution:{1:0,2:0,3:1,4:3,5:8}},pagination:{page:1,limit:6,total:12,totalPages:2}});
 if(u.includes('/coupons/available')) return J([{code:'WELCOME10',description:'10% off your first order',discountType:'percentage',discountValue:10,maxDiscountAmount:1000,minimumOrderValue:2999,startsAt:'2026-01-01',endsAt:'2026-12-31',firstOrderOnly:true,applicableProductIds:[]},{code:'FREESHIP',description:'Free shipping',discountType:'free_shipping',discountValue:0,maxDiscountAmount:null,minimumOrderValue:0,startsAt:'2026-01-01',endsAt:null,firstOrderOnly:false,applicableProductIds:[]}]);
 if(u.includes('/marketing/featured-collection')){r.setHeader('content-type','application/json');return r.end(JSON.stringify({success:true,data:{_id:'m1',name:'Festive',slug:'festive',description:'d',type:'featured_collection',status:'active',startsAt:null,endsAt:null,budget:0,metadata:{image:'/images/home/featured-collection-campaign.jpg',imageAlt:'Festive',eyebrow:'Featured Collection',title:'The Festive Edit',description:'Rich fabrics and hand finished detail for the season.',ctaLabel:'Explore the edit',ctaHref:'/collections/festive',brandLabel:'Aayesha',bottomLabel:'Limited',bottomTitle:'Festive 2026'},createdBy:null,updatedBy:null,createdAt:'',updatedAt:''}}));}
 if(u.includes('/marketing/promotional-banner')){r.setHeader('content-type','application/json');return r.end(JSON.stringify({success:true,data:{_id:'m2',name:'Promo',slug:'promo',description:'d',type:'promotional_banner',status:'active',startsAt:null,endsAt:null,budget:0,metadata:{placement:'promotional_banner',image:'/images/home/promotional-banner.jpg',imageAlt:'Promo',href:'/shop',ctaLabel:'Shop now',eyebrow:'Offer',title:'Complimentary shipping',description:'On orders above 2,999'},createdBy:null,updatedBy:null,createdAt:'',updatedAt:''}}));}
 if(u.includes('/auth/register')){r.statusCode=201;r.setHeader('content-type','application/json');return r.end(JSON.stringify({success:true,data:{user,requiresEmailVerification:false}}));}
 if(u.includes('/auth/email-verification/send')){r.setHeader('content-type','application/json');return r.end(JSON.stringify({success:true,data:{alreadyVerified:false}}));}
 if(u.includes('/auth/email-verification/confirm')){r.setHeader('content-type','application/json');return r.end(JSON.stringify({success:true,data:{user:{...user,emailVerified:true}}}));}
 if(u.includes('/auth/refresh')||u.includes('/auth/login')){r.setHeader('content-type','application/json');return r.end(JSON.stringify({success:true,data:{user,accessToken:'tok'}}));}
 if(u.includes('/auth/me')){r.setHeader('content-type','application/json');return r.end(JSON.stringify({success:true,data:{user}}));}
 if(u.endsWith('/carts')&&q.method==='POST'){return setTimeout(()=>{r.setHeader('content-type','application/json');r.end(JSON.stringify({success:true,data:{id:'c1',userId:'u1',items:[{productId:'p3',quantity:1,product:cp(3)}]}}));},700);}
 if(u.endsWith('/carts')){r.setHeader('content-type','application/json');return r.end(JSON.stringify({success:true,data:{id:'c1',userId:'u1',items:[{productId:'p0',quantity:1,product:cp(0)},{productId:'p3',quantity:2,product:cp(3)}]}}));}
 if(u.includes('/customer/addresses')){r.setHeader('content-type','application/json');return r.end(JSON.stringify({success:true,data:[{id:'a1',userId:'u1',name:'Aisha Khan',phone:'9876543210',addressLine:'12 Rose Lane, Model Town',city:'Delhi',state:'Delhi',pincode:'110009',landmark:'Near park',isDefault:true,createdAt:'',updatedAt:''}]}));}

 if(u.endsWith('/products')) data={products,pagination:{page:1,limit:24,total:8,totalPages:1}};
 else if(u.endsWith('/categories')) data=cats;
 else if(/\/products\//.test(u)){const id=u.split('/').pop();const pr=products.find(x=>x.id===id);if(!pr){r.statusCode=404;r.setHeader('content-type','application/json');return r.end(JSON.stringify({success:false,error:{code:'NOT_FOUND',message:'Product not found'}}));}data={product:pr};}
 else data={hero:{enabled:true,slides:[1,2,3].map(i=>({id:'h'+i,eyebrow:'The New Edit',title:'Contemporary Indian Womenswear',subtitle:'Festive 2026',description:'Hand finished silhouettes for every occasion.',image:'/images/hero/hero-0'+i+'-desktop.jpg',mobileImage:'/images/hero/hero-0'+i+'-mobile.jpg',href:'/shop',buttonLabel:'Shop Now',sortOrder:i,isActive:true,startsAt:null,endsAt:null}))},
 brandStory:{enabled:true,eyebrow:'Our Story',number:'01',title:'Made for moments worth remembering',descriptions:['Aayesha Fashion designs contemporary Indian womenswear.','Every piece is finished by hand.'],ctaLabel:'Read our story',ctaHref:'/our-story',image:'/images/home/brand-story.jpg',imageAlt:'Story',caption:'Atelier',brandLabel:'Aayesha',statement:'Quiet confidence.'},
 whyChooseUs:{enabled:true,eyebrow:'Why Aayesha',number:'02',title:'Crafted with care',description:'What sets us apart.',values:[{id:'a',title:'Tailored fit',description:'Cut for you.',icon:'scissors',sortOrder:1,isActive:true},{id:'b',title:'Fine fabrics',description:'Chosen with care.',icon:'gem',sortOrder:2,isActive:true},{id:'c',title:'Made with love',description:'By our artisans.',icon:'heart',sortOrder:3,isActive:true},{id:'d',title:'Occasion ready',description:'For every moment.',icon:'sparkles',sortOrder:4,isActive:true}],closingStatement:'Designed to be lived in.'},
 testimonials:{enabled:true,testimonials:[1,2,3].map(i=>({id:'t'+i,quote:'Beautiful fabric and a perfect fit. I received so many compliments.',name:'Customer '+i,location:'Delhi',image:'/images/instagram/instagram-0'+i+'.jpg',imageAlt:'c',sortOrder:i,isActive:true}))},
 newsletter:{enabled:true,eyebrow:'Stay in the know',title:{lineOne:'Discover the next',lineTwo:'Aayesha edit.'},description:'Be first to see new collections.',inputPlaceholder:'Your email address',buttonLabel:'Join',disclaimer:'Unsubscribe anytime.'},
 instagram:{enabled:true,eyebrow:'Follow along',title:{lineOne:'Aayesha',lineTwo:'on Instagram'},handle:'@aayeshafashion',instagramUrl:'https://instagram.com',ctaLabel:'Follow',posts:[1,2,3,4,5,6].map(i=>({id:'i'+i,src:'/images/instagram/instagram-0'+i+'.jpg',alt:'p',href:'#',sortOrder:i,isActive:true}))}};
 r.setHeader('content-type','application/json'); r.end(JSON.stringify({success:true,data}));
}).listen(5000);
